name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FLUTTER_SUPPRESS_ANALYTICS: true
      DART_SUPPRESS_ANALYTICS: true

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1'
          channel: 'stable'

      - name: Disable Flutter analytics
        run: flutter config --no-analytics

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build APK
        run: flutter build apk

      - name: Build Web
        run: flutter build web

      - name: Build iOS (macOS only)
        if: runner.os == 'macOS'
        run: flutter build ios --no-codesign

      - name: Build APK
        run: flutter build apk

      - name: Build Web
        run: flutter build web

      - name: Build iOS (macOS only)
        if: runner.os == 'macOS'
        run: flutter build ios --no-codesign

